CREATE DATABASE WebChatCNPM
CREATE table [GroupChat](
	Id BIGINT primary key identity(1,1),
	ObjectGuid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	IdUserCreate BIGINT NOT NULL,
	[Name] nvarchar(100) NOT NULL,
	isDelete BIT NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
	LastUpdate DATETIME NOT NULL
)
CREATE table [User](
	Id BIGINT PRIMARY KEY identity(1,1),
	ObjectGuid  UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	Email NVARCHAR(250) NOT NULL,
	[Username] VARCHAR(250) NOT NULL,
	PasswordHash VARBINARY(MAX) NOT NULL,
	PasswordSalt VARBINARY(MAX) NOT NULL,
	[Name] NVARCHAR(250) NOT NULL,
	Sex BIT NOT NULL,
	BirthDate DATETIME NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1,
	CreateDate DATETIME NOT NULL,
	LastUpdate DATETIME NOT NULL
)

CREATE TABLE Members(
	IdUser BIGINT PRIMARY KEY NOT NULL,
	IDGroup BIGINT PRIMARY KEY NOT NULL,
	NickName NVARCHAR(250) NULL,
	IdModAdd BIGINT NOT NULL,
	JoinDate DateTime NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1,
)

CREATE TABLE [Mod](
	IDUserDelegacyed BIGINT NOT NULL,
	IdMemberDelegacy BIGINT NOT NULL,
	IdPosition BIGINT NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1,
	DelegacyDate DATETIME NOT NULL,
	LastUpdate DATETIME NOT NULL
)

CREATE TABLE Position(
	Id BIGINT PRIMARY KEY identity(1,1),
	[Name] NVARCHAR(250) NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1,
	CreateDate DATETIME NOT NULL,
)

CREATE TABLE Delegacy(
	IDPosition BIGINT PRIMARY KEY,
	IDPermision BIGINT PRIMARY KEY
	IsDelete BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL DEFAULT 1,
	LastUpdate DATETIME NOT NULL
)

CREATE TABLE Permision(
	ID BIGINT PRIMARY KEY identity(1,1),
	[NamePermision] NVARCHAR(250) NOT NULL,
	ActionName NVARCHAR(250) NOT NULL,
	ActionCode VARCHAR(250) NULL
)

CREATE TABLE BandList(
	IdGroupChat BIGINT NOT NULL,
	IdUser BIGINT NOT NULL,
	CreateDate DATETIME NOT NULL,
	IdAdmintrastor BIGINT NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	LastUpdate DATETIME NOT NULL
)


CREATE TABLE FileUpload(
	ID BIGINT PRIMARY KEY identity(1,1),
	FileAttachGUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	IDMessage BIGINT NOT NULL ,
    UserIDCreate INT NOT NULL,
    [FileName] NVARCHAR(250) NOT NULL,
    FileExttension VARCHAR(50) NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	
)

CREATE TABLE [Message](
	ID BIGINT PRIMARY KEY identity(1,1),
	ObjectGUID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	UserIDCreate INT NOT NULL,
	IDChanel BIGINT NOT NULL,
	[MessageType] BIGINT NOT NULL,
	MessageContent TEXT NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	CreateDate DateTime NOT NULL,
	LastUpdate DateTime NOT NULL,
	IsPrivateChat BIT NOT NULL
)

CREATE TABLE KeyWord(
	ID BIGINT PRIMARY,
	IDGroupChat BIGINT ,
	IDMod BIGINT ,
	KeyWord NVARCHAR(250) NOT NULL,
	ReplacedWord NVARCHAR(250) NOT NULL,
	CreateDate DateTime NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0
)


CREATE TABLE Friendship(
	IDUser1 BIGINT NOT NULL,
	IDUser2 BIGINT NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	CreateDate DateTime NOT NULL
)

CREATE TABLE FriendshipRegisterHistory(
	IDUserSend BIGINT NOT NULL,
	IDUserReceive BIGINT NOT NULL,
	IsDelete BIT NOT NULL DEFAULT 0,
	CreateDate DateTime NOT NULL
)
